package com.example.wartungsapp;

import android.net.Uri;
import android.os.Parcel;
import android.os.Parcelable;
import android.widget.Toast;

import androidx.annotation.NonNull;

public class Vehicle implements Parcelable {

    private MainActivity mainActivity;
    private String name;
    private int mileage;
    private int monthlyMileage;
    private Uri imageURI;

    public Vehicle(String name, int mileage, int monthlyMileage,  Uri imageURI) {
        this.mainActivity = new MainActivity();
        this.name = name;
        this.mileage = mileage;
        this.monthlyMileage = monthlyMileage;
        this.imageURI = imageURI;
    }

    public void save() {    // deprecated
        //TODO: save current instance
        mainActivity.addVehicle(this);
    }

    // just created these, might delete some later if not needed
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getMileage() {
        return mileage;
    }

    public void setMileage(int mileage) {
        this.mileage = mileage;
    }

    public Uri getImageURI() {
        return imageURI;
    }

    public void setImageURI(Uri imageURL) {
        this.imageURI = imageURI;
    }

    @Override
    public String toString() {
        return "Vehicle{" +
                "name='" + name + '\'' +
                ", mileage=" + mileage +
                ", monthlyMileage=" + monthlyMileage +
                ", imageURI='" + imageURI + '\'' +
                '}';
    }

    protected Vehicle(Parcel in) {
        name = in.readString();
        mileage = in.readInt();
        monthlyMileage = in.readInt();
        imageURI = in.readParcelable(Uri.class.getClassLoader());   //GPT
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        dest.writeString(name);
        dest.writeInt(mileage);
        dest.writeInt(monthlyMileage);
        dest.writeParcelable(imageURI, flags);
    }

    // recreates a vehicle from a parcel, auto-generated by IDE
    public static final Creator<Vehicle> CREATOR = new Creator<Vehicle>() {
        @Override
        public Vehicle createFromParcel(Parcel in) {
            return new Vehicle(in);
        }

        @Override
        public Vehicle[] newArray(int size) {
            return new Vehicle[size];
        }
    };
}
